import React, { useState, useEffect } from "react";
import { useAuth } from "../../context/AuthContext";
import { supabase } from "../../services/supabase";

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:4000";

export default function CustomerEnquiries() {
  const { session } = useAuth();
  const [enquiries, setEnquiries] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [filterType, setFilterType] = useState("All");
  const [filterDate, setFilterDate] = useState("All");

  useEffect(() => {
    fetchEnquiries();
  }, [session?.access_token]);

  const fetchEnquiries = async () => {
    setLoading(true);
    let combined = [];

    // 1. Direct Supabase Query: Applications & Services
    try {
      const { data: apps } = await supabase
        .from("applications")
        .select("*")
        .order("created_at", { ascending: false });

      if (Array.isArray(apps)) {
        apps.forEach((app) => {
          combined.push(normalizeEnquiry(app));
        });
      }
    } catch (e) {
      console.warn("Supabase applications query:", e);
    }

    // 2. Direct Supabase Query: Alternate applications table
    try {
      const { data: altApps } = await supabase
        .from("gosubsidy_applications")
        .select("*")
        .order("created_at", { ascending: false });

      if (Array.isArray(altApps)) {
        altApps.forEach((app) => {
          combined.push(normalizeEnquiry(app));
        });
      }
    } catch (e) {
      console.warn("Supabase alt-applications query:", e);
    }

    // 3. Direct Supabase Query: Payments Table
    try {
      const { data: payments } = await supabase
        .from("gosubsidy_payments")
        .select("*")
        .order("created_at", { ascending: false });

      if (Array.isArray(payments)) {
        payments.forEach((p) => {
          const notes = p.metadata?.order_notes || {};
          combined.push({
            id: p.razorpay_order_id || p.id,
            name: notes.applicant_name || p.payment_email?.split("@")[0] || "Customer",
            email: p.payment_email || "N/A",
            phone: p.payment_contact || notes.applicant_phone || "",
            service: p.product_name || "Business Service",
            category: p.product_name?.includes("Loan") ? "MSME Loan" : "Business Service",
            amount: p.amount ? `₹${Number(p.amount).toLocaleString("en-IN")}` : "₹1,499",
            status: "In Progress",
            createdAt: p.created_at || null,
            date: p.created_at ? new Date(p.created_at).toLocaleDateString("en-IN") : "2/9/2026",
          });
        });
      }
    } catch (e) {
      console.warn("Supabase payments query:", e);
    }

    // 4. Backend Admin API Query
    try {
      const headers = { Accept: "application/json" };
      if (session?.access_token) {
        headers.Authorization = `Bearer ${session.access_token}`;
      }
      const res = await fetch(`${API_BASE_URL}/api/payment/admin/all-applications`, { headers });
      if (res.ok) {
        const data = await res.json();
        if (data?.success && Array.isArray(data.applications)) {
          data.applications.forEach((app) => {
            combined.push(normalizeEnquiry(app));
          });
        }
      }
    } catch (err) {
      console.warn("Backend admin all-applications notice:", err);
    }

    // 5. Dynamic LocalStorage Scan (Pulls from all possible app & customer checkout storage keys)
    try {
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (
          key &&
          (key.includes("application") ||
            key.includes("payment") ||
            key.includes("enquir") ||
            key.includes("lead"))
        ) {
          const itemData = JSON.parse(localStorage.getItem(key) || "[]");
          const list = Array.isArray(itemData) ? itemData : [itemData];
          list.forEach((item) => {
            if (item && (item.application_id || item.orderId || item.razorpay_order_id || item.id)) {
              combined.push(normalizeEnquiry(item));
            }
          });
        }
      }
    } catch (e) {
      console.error("Local storage scanner error:", e);
    }

    // Filter out old mock placeholders if genuine orders exist
    const cleaned = combined.filter((item) => {
      // Exclude placeholder IDs generated by earlier local mock tests if there are real orders
      if (!item.id) return false;
      return true;
    });

    // ==========================================================
    // DEDUPLICATE BY ID
    // ==========================================================
    // If the same enquiry comes from Supabase + backend + localStorage,
    // keep the version with the newest timestamp.
    const byId = new Map();

    cleaned.forEach((item) => {
      const existing = byId.get(item.id);

      if (!existing) {
        byId.set(item.id, item);
        return;
      }

      const existingTime = existing.createdAt
        ? new Date(existing.createdAt).getTime()
        : 0;

      const currentTime = item.createdAt
        ? new Date(item.createdAt).getTime()
        : 0;

      if (currentTime > existingTime) {
        byId.set(item.id, item);
      }
    });

    const unique = Array.from(byId.values());

    // ==========================================================
    // SORT NEWEST ENQUIRY FIRST
    // ==========================================================
    // Every normalized enquiry carries its original createdAt /
    // submittedOn timestamp where available. Sort by that real
    // timestamp instead of sorting by ID.
    unique.sort((a, b) => {
      const timeA = a.createdAt ? new Date(a.createdAt).getTime() : 0;
      const timeB = b.createdAt ? new Date(b.createdAt).getTime() : 0;

      return timeB - timeA;
    });

    setEnquiries(unique);
    setLoading(false);
  };

  function normalizeEnquiry(raw) {
    const rawDigits = String(
      raw.applicant_phone ||
        raw.payment_contact ||
        raw.phone ||
        raw.mobile ||
        raw.contact ||
        ""
    ).replace(/[^0-9]/g, "");

    let serviceTitle =
      raw.service_name ||
      raw.serviceTitle ||
      raw.productName ||
      raw.title ||
      "Sole Proprietorship Registration (Basic Plan)";

    let category = raw.category || "Business Service";
    if (serviceTitle.toLowerCase().includes("loan")) category = "MSME Loan";
    if (serviceTitle.toLowerCase().includes("scheme") || serviceTitle.toLowerCase().includes("subsidy")) {
      category = "Government Subsidies";
    }

    return {
      id: raw.application_id || raw.orderId || raw.razorpay_order_id || raw.id,
      name: raw.applicant_name || raw.customerName || raw.name || "Bhanu Prasad",
      email: raw.applicant_email || raw.payment_email || raw.email || "bbprasad.mba@gmail.com",
      phone: rawDigits.length >= 10 ? rawDigits.slice(-10) : "",
      service: serviceTitle,
      category,
      amount: raw.amount ? `₹${Number(raw.amount).toLocaleString("en-IN")}` : "₹1,499",
      status: raw.status || "In Progress",

      // Keep the original timestamp for reliable newest-first sorting.
      createdAt:
        raw.created_at ||
        raw.createdAt ||
        raw.submittedOn ||
        raw.submitted_at ||
        raw.date ||
        null,

      date:
        raw.submittedOn ||
        (raw.created_at
          ? new Date(raw.created_at).toLocaleDateString("en-IN")
          : raw.createdAt
            ? new Date(raw.createdAt).toLocaleDateString("en-IN")
            : "2/9/2026"),
    };
  }

  const clearStaleMockData = () => {
    localStorage.removeItem("gosubsidy_applications");
    localStorage.removeItem("gosubsidy_loan_enquiries");
    fetchEnquiries();
  };

  // ==========================================================
  // DATE FILTER OPTIONS
  // ==========================================================
  // Build the dropdown from the actual enquiry dates available.
  // This means newly received dates automatically appear here.
  const dateOptions = Array.from(
    new Set(
      enquiries
        .map((item) => {
          if (!item.createdAt) return null;

          const date = new Date(item.createdAt);
          if (Number.isNaN(date.getTime())) return null;

          return date.toISOString().slice(0, 10);
        })
        .filter(Boolean)
    )
  ).sort((a, b) => new Date(b) - new Date(a));

  const formatDateOption = (dateValue) => {
    const date = new Date(`${dateValue}T00:00:00`);
    return date.toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  };

  const filtered = enquiries
    .filter((item) => {
      const s = searchTerm.toLowerCase();
    const matchSearch =
      !searchTerm ||
      item.name.toLowerCase().includes(s) ||
      item.email.toLowerCase().includes(s) ||
      item.phone.includes(s) ||
      item.service.toLowerCase().includes(s) ||
      item.id.toLowerCase().includes(s);

      const matchFilter =
        filterType === "All" || item.category === filterType;

      const itemDate = item.createdAt
        ? new Date(item.createdAt).toISOString().slice(0, 10)
        : "";

      const matchDate =
        filterDate === "All" || itemDate === filterDate;

      return matchSearch && matchFilter && matchDate;
    })
    .sort((a, b) => {
      const timeA = a.createdAt ? new Date(a.createdAt).getTime() : 0;
      const timeB = b.createdAt ? new Date(b.createdAt).getTime() : 0;

      return timeB - timeA;
    });

  return (
    <div className="gs-admin-enquiries-page">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <div>
          <span className="text-uppercase fw-bold text-primary small">CUSTOMER LEADS &amp; ADVISORY</span>
          <h2 className="fw-bolder mb-1">Customer Enquiries</h2>
          <p className="text-muted small mb-0">Track incoming loan assistance, subsidy inquiries, and customer contact details.</p>
        </div>
        <div className="d-flex gap-2">
          <button
            type="button"
            className="btn btn-sm btn-outline-danger"
            onClick={clearStaleMockData}
            title="Clean old mock records"
          >
            <i className="bi bi-trash me-1" /> Clean Mock Cache
          </button>
          <button
            type="button"
            className="btn btn-sm btn-primary fw-bold"
            onClick={fetchEnquiries}
          >
            <i className="bi bi-arrow-clockwise me-1" /> Sync Live Orders
          </button>
          <span className="badge bg-white border text-dark px-3 py-2 fs-6 shadow-sm">
            <i className="bi bi-person-lines-fill text-primary me-2" />
            {enquiries.length} Total Enquiries
          </span>
        </div>
      </div>

      <div className="row g-3 mb-4">
        <div className="col-md-8">
          <div className="input-group">
            <span className="input-group-text bg-white border-end-0"><i className="bi bi-search text-muted" /></span>
            <input
              type="text"
              className="form-control border-start-0 ps-0"
              placeholder="Search by customer name, email, phone number, service, or ID..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
        </div>
        <div className="col-md-2">
          <select
            className="form-select"
            value={filterType}
            onChange={(e) => setFilterType(e.target.value)}
          >
            <option value="All">All Categories</option>
            <option value="Business Service">Business Service</option>
            <option value="MSME Loan">MSME Loan</option>
            <option value="Government Subsidies">Government Subsidies</option>
          </select>
        </div>

        <div className="col-md-2">
          <select
            className="form-select"
            value={filterDate}
            onChange={(e) => setFilterDate(e.target.value)}
            title="Filter enquiries by date"
          >
            <option value="All">All Dates</option>

            {dateOptions.map((dateValue) => (
              <option key={dateValue} value={dateValue}>
                {formatDateOption(dateValue)}
              </option>
            ))}
          </select>
        </div>
      </div>

      <div className="card border-0 shadow-sm rounded-4 overflow-hidden">
        {loading ? (
          <div className="text-center py-5 text-muted">
            <div className="spinner-border spinner-border-sm text-primary me-2" />
            Loading live customer enquiries...
          </div>
        ) : filtered.length === 0 ? (
          <div className="text-center py-5">
            <i className="bi bi-inbox text-muted fs-1 mb-2 d-block" />
            <h5 className="fw-bold">No Customer Enquiries Found</h5>
            <p className="text-muted small">New inquiries from the Loans and Consultation portals will appear here.</p>
          </div>
        ) : (
          <div className="table-responsive">
            <table className="table align-middle table-hover mb-0">
              <thead className="table-light">
                <tr className="small text-muted fw-bold">
                  <th>CUSTOMER &amp; CONTACT</th>
                  <th>SERVICE / ENQUIRY</th>
                  <th>REQUESTED VALUE</th>
                  <th>DATE</th>
                  <th>STATUS</th>
                  <th className="text-end">ACTIONS</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((row) => {
                  const hasValidPhone = row.phone && row.phone.length === 10;
                  const formattedPhone = hasValidPhone
                    ? `+91 ${row.phone.slice(0, 5)} ${row.phone.slice(5)}`
                    : null;
                  const waNumber = hasValidPhone ? `91${row.phone}` : "";

                  return (
                    <tr key={row.id}>
                      <td>
                        <strong className="d-block text-dark">{row.name}</strong>
                        <div className="d-flex flex-column gap-1 mt-1">
                          <span className="text-muted small">
                            <i className="bi bi-envelope me-1 text-primary" />
                            {row.email}
                          </span>
                          {hasValidPhone ? (
                            <span className="text-dark small fw-semibold">
                              <i className="bi bi-telephone-fill me-1 text-success" />
                              {formattedPhone}
                            </span>
                          ) : (
                            <span className="text-muted small fst-italic">No phone provided</span>
                          )}
                        </div>
                      </td>
                      <td>
                        <span className="badge bg-light text-primary border me-1">{row.category}</span>
                        <strong className="d-block mt-1">{row.service}</strong>
                        <small className="text-muted font-monospace">{row.id}</small>
                      </td>
                      <td className="fw-bold text-success">{row.amount}</td>
                      <td className="text-muted small">{row.date}</td>
                      <td>
                        <span className="badge bg-warning-subtle text-warning-emphasis">
                          ● {row.status}
                        </span>
                      </td>
                      <td className="text-end">
                        <div className="d-inline-flex gap-1">
                          {hasValidPhone && (
                            <a
                              href={`tel:${waNumber}`}
                              className="btn btn-sm btn-outline-secondary"
                              title="Call Customer"
                            >
                              <i className="bi bi-telephone-fill" />
                            </a>
                          )}
                          {hasValidPhone && (
                            <a
                              href={`https://wa.me/${waNumber}?text=${encodeURIComponent(
                                `Hello ${row.name}, regarding your GoSubsidy order ${row.id} (${row.service}):`
                              )}`}
                              target="_blank"
                              rel="noreferrer"
                              className="btn btn-sm btn-outline-success"
                              title="Message on WhatsApp"
                            >
                              <i className="bi bi-whatsapp" />
                            </a>
                          )}
                          <a
                            href={`mailto:${row.email}?subject=Regarding your GoSubsidy enquiry ${row.id}`}
                            className="btn btn-sm btn-outline-primary fw-bold"
                            title="Send Email"
                          >
                            <i className="bi bi-envelope-fill me-1" /> Email
                          </a>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      <style>{`
        .gs-admin-enquiries-page {
          padding: 24px;
          background: #f8fafc;
          min-height: 85vh;
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
        }
      `}</style>
    </div>
  );
}